name: Create Cavatica Projects

on:
  issues:
    types:
      [opened, reopened]

jobs:
  create_cavatica_project:
    runs-on: ubuntu-latest
    environment: cavatica-prod
    permissions:
      contents: read
      issues: write
    strategy:
      matrix:
        python-version: ['3.12.9']
    if: contains(github.event.issue.title, '[Project Creation]')

    steps:
      - name: Checkout API Repo
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Run Project Creation Script
        env:
          BODY: ${{ github.event.issue.body }}
          URL: ${{ github.event.issue.url }}
        run: |
          python scripts/create_project.py \
          --token ${{ secrets.CAVATICA_TOKEN }} \
          --run
      - name: Close Issue
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
        run: |
          gh issue close "$ISSUE_NUMBER" --comment "Deployment finished. Issue closed automatically by CI/CD."
